- name: "Install helm"
  ansible.builtin.unarchive:
    src: "{{ helm_url }}"
    dest: /usr/local/bin/
    creates: /usr/local/bin/helm
    exclude:
      - linux-amd64/README.md
      - linux-amd64/LICENSE
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Install k9s
  ansible.builtin.unarchive:
    src: "{{ k9s_url }}"
    dest: /usr/local/bin/
    creates: /usr/local/bin/k9s
    exclude:
      - README.md
      - LICENSE
    remote_src: true
