---
- name: Add ingress controller helm repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "{{ traefik_repo_url }}"

- name: Deploy traefik ingress controller
  kubernetes.core.helm:
    name: traefik
    chart_ref: "{{ traefik_chart_ref }}"
    chart_version: "{{ traefik_chart_version }}"
    release_namespace: ingress-traefik
    create_namespace: true
    update_repo_cache: true
