---
- name: Add ingress controller helm repository
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: "{{ traefik_repo_url }}"

- name: Deploy traefik ingress controller
  kubernetes.core.helm:
    name: traefik
    chart_ref: "{{ traefik_chart_ref }}"
    chart_version: "{{ traefik_chart_version }}"
    release_namespace: ingress-traefik
    create_namespace: true
    update_repo_cache: true
    values:
      # Show traefik service IP in ingress resource
      providers:
        kubernetesIngress:
          publishedService:
            enabled: true

# Deploy traefik dashboard with web entrypoint
- name: Deploy traefik web dashboard
  when: traefik_deploy_dashboard
  kubernetes.core.k8s:
    state: present
    src: files/ingressroute-dashboard.yaml
