helm_version: 3.13.3
helm_url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"

k9s_version: 0.31.7
k9s_url: "https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_amd64.tar.gz"
