#!/usr/bin/env bash

set -euxo pipefail

: === Setup static IP: ${IP_ADDRESS:-Error} ===
cat <<EOF > /etc/netplan/01-netcfg.yaml
# Generated by Vagrant
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      addresses: [${IP_ADDRESS}/24]
      gateway4: 172.16.0.1
      nameservers:
        addresses: [188.117.143.11, 8.8.8.8, 172.16.0.1]
EOF