#!/usr/bin/env bash

set -euxo pipefail

if ! ip -4 address | grep -q "${IP_ADDRESS}"; then

  : === Setup static IP: ${IP_ADDRESS:-Error} ===
  cat <<EOF > /etc/netplan/01-netcfg.yaml
# Generated by Vagrant
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: false
      dhcp6: false
      addresses: [${IP_ADDRESS}/24]
      gateway4: 172.16.0.1
      nameservers:
        addresses: [188.117.143.11, 8.8.8.8, 172.16.0.1]
EOF

  netplan apply
else
  : === Static IP: ${IP_ADDRESS:-Error} already set, skipping ===
fi

# : === Wait for static IP ===
# while ip -4 address | grep -qv "${IP_ADDRESS}"; do echo "Waiting for static IP" && sleep 2; done
