---
- name: Configure Kubernetes Masters
  hosts: kmaster*
  connection: local
  become: true
  tasks:

    # K8s prerequisites
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
    - name: Disable swap
      ansible.builtin.command: swapoff -a

    # https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
    - name: Disable swap permanently in fstab (comment out)
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    # https://kubernetes.io/docs/reference/networking/ports-and-protocols/
    - name: Open required firewall ports
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: tcp
        direction: in
      loop:
        - { port: 22 }
        - { port: 443 }
        - { port: 6443 }
        - { port: 10250 }
        - { port: 10257 }
        - { port: 10259 }
        - { port: 2379:2380 }
        - { port: 60000:61000 }

    - name: Containerd module prerequisites
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { src: "modules_k8s.conf.j2", dest: "/etc/modules-load.d/k8s.conf" }
        - { src: "sysctl_k8s.conf.j2", dest: "/etc/sysctl.d/k8s.conf" }

    - name: Apply sysctl parameters
      ansible.builtin.shell:
        cmd: |
          modprobe overlay
          modprobe br_netfilter
          sysctl --system

    - name: Add K8s apt key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add K8s apt repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install container runtime and K8s binaries
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - containerd
          - kubeadm=1.25.5-00
          - kubelet=1.25.5-00
          - kubectl=1.25.5-00
        state: present
        update_cache: true
        autoclean: true

    - name: Generate default containerd config
      ansible.builtin.shell:
        cmd: |
          mkdir -p /etc/containerd
          containerd config default > /etc/containerd/config.toml

    - name: Start K8s services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - containerd
        - kubelet

    # Initialize K8s cluster, run only on primary master
    - name: Initialize K8s cluster with kubeadm
      block:
        - name: Initialize K8s cluster with kubeadm
          ansible.builtin.command: kubeadm init --control-plane-endpoint="{{ vip }}:6443" --upload-certs --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=192.168.0.0/16

        - name: Install CNI - calico
          ansible.builtin.command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml
          environment:
            KUBECONFIG: /etc/kubernetes/admin.conf

        - name: Generate K8s cluster join command
          ansible.builtin.command: kubeadm token create --print-join-command
          register: join_command

        - name: Write join command to local file
          ansible.builtin.copy:
            content: "{{ join_command.stdout_lines[0] }}"
            dest: /home/vagrant/join-command
      when: ansible_hostname == primary_master_hostname

    # TODO: This does not work!
    - name: Join other masters to cluster
      ansible.builtin.command: "{{ join_command.stdout_lines[0] }}"
      when: not ansible_hostname == primary_master_hostname

    - name: Create .kube directory for vagrant user
      ansible.builtin.file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant

    - name: Copy kubeconfig for vagrant user
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: true
        owner: vagrant
        group: vagrant
        mode: '0600'
