---
- name: Configure Kubernetes Workers
  hosts: kw*
  connection: local
  become: true
  tasks:

    # K8s prerequisites
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
    - name: Disable swap
      ansible.builtin.command: swapoff -a

    # https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
    - name: Disable swap permanently in fstab (comment out)
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    # https://kubernetes.io/docs/reference/networking/ports-and-protocols/
    - name: Open required firewall ports
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: tcp
        direction: in
      loop:
        - { port: 10250 }
        - { port: 30000:32767 }

    - name: Containerd module prerequisites
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - { src: "modules_k8s.conf.j2", dest: "/etc/modules-load.d/k8s.conf" }
        - { src: "sysctl_k8s.conf.j2", dest: "/etc/sysctl.d/k8s.conf" }

    - name: Apply sysctl parameters
      ansible.builtin.shell:
        cmd: |
          modprobe overlay
          modprobe br_netfilter
          sysctl --system

    - name: Add K8s apt key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add K8s apt repository into sources list
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install container runtime and K8s binaries
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - containerd
          - kubeadm=1.25.5-00
          - kubelet=1.25.5-00
          - kubectl=1.25.5-00
        state: present
        update_cache: true
        autoclean: true

    - name: Generate default containerd config
      ansible.builtin.shell:
        cmd: |
          mkdir -p /etc/containerd
          containerd config default > /etc/containerd/config.toml

    - name: Start K8s services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - containerd
        - kubelet

    # Fetch join command from primary master, ugly but works..
    - name: Fetch join command from primary master
      ansible.builtin.shell:
        cmd: >-
          /usr/bin/sshpass -p "vagrant"
          scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
          vagrant@172.16.0.101:/home/vagrant/join-command /home/vagrant/join-command
          && chown vagrant:vagrant /home/vagrant/join-command
      register: copy_join_cmd
      until: copy_join_cmd is not failed
      retries: 10
      delay: 10

    - name: Join node to cluster
      ansible.builtin.shell:
        cmd: |
          # Extract only worker join command - rudimentary but works
          grep -A3 "kubeadm join" /home/vagrant/join-command | tail -2 | tee /home/vagrant/join-command
          chmod +x /home/vagrant/join-command && bash /home/vagrant/join-command
