---
- name: Configure Kubernetes Workers
  hosts: kw*
  connection: local
  become: true
  tasks:

    # K8s prerequisites
    # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
    - name: Disable swap
      ansible.builtin.command: swapoff -a

    # https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
    - name: Disable swap permanently in fstab (comment out)
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    # https://kubernetes.io/docs/reference/networking/ports-and-protocols/
    - name: Open required firewall ports
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: tcp
        direction: in
      loop:
        - { port: 10250 }
        - { port: 30000:32767 }

    - name: Include containerd setup tasks
      ansible.builtin.include_role:
        name: containerd

    # Fetch join command from primary master, ugly but works..
    - name: Fetch join command from primary master
      ansible.builtin.shell:
        cmd: >-
          /usr/bin/sshpass -p "vagrant"
          scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
          vagrant@172.16.0.101:/home/vagrant/join-command /home/vagrant/join-command
          && chown vagrant:vagrant /home/vagrant/join-command
      register: copy_join_cmd
      until: copy_join_cmd is not failed
      retries: 10
      delay: 10

    - name: Join node to cluster
      ansible.builtin.shell:
        cmd: |
          # Extract only worker join command - rudimentary but works
          set -o pipefail
          grep -A3 "kubeadm join" /home/vagrant/join-command | tail -2 | tee /home/vagrant/join-command
          chmod +x /home/vagrant/join-command && bash /home/vagrant/join-command
      args:
        executable: /usr/bin/bash
