---
- name: Configure loadbalancer
  hosts: loadbalancer*
  connection: local
  become: yes
  tasks:
    - name: Install LB packages
      ansible.builtin.apt:
        name:
          - keepalived
          - haproxy
        state: present
        update_cache: true
        autoclean: true
