---
- name: Configure loadbalancer
  hosts: loadbalancer*
  connection: local
  become: true
  tasks:
    - name: Install LB packages
      ansible.builtin.apt:
        name:
          - keepalived
          - haproxy
        state: present
        update_cache: true
        autoclean: true

    - name: Create API check script
      ansible.builtin.template:
        src: check_apiserver.sh.j2
        dest: /etc/keepalived/check_apiserver.sh
        owner: root
        group: root
        mode: '0755'

    - name: Create Keepalived configuration
      ansible.builtin.template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Keepalived

    - name: Create HAProxy configuration
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0644'
      notify: Restart HAProxy

  handlers:
    - name: Restart Keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
        enabled: true

    - name: Restart HAProxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
        enabled: true
